---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- ansible.builtin.import_tasks: firewall.yml
  when:
    - wireguard_firewalld_config_enabled | bool

- name: Install Wireguard
  ansible.builtin.package:
    name:
     - wireguard
    state: present
    update_cache: yes

- name: Enable IPv4 packet forwarding in sysctl.conf
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_file: /etc/sysctl.conf
    sysctl_set: yes
    state: present
    reload: yes

- name: Verify that Wireguard configuration directory exists
  ansible.builtin.stat:
    path: "{{ item }}"
  with_items:
    - /etc/wireguard
  check_mode: no

- name: Copy wg0.conf
  ansible.builtin.template:
    src: templates/wg0.conf.j2
    dest: "/etc/wireguard/wg0.conf"
    owner: root
    group: root
    mode: 0600
  notify:
    - Restart wireguard

- name: Start and enable wireguard
  ansible.builtin.systemd:
    name: wg-quick@wg0
    enabled: yes
    state: started
    masked: no
  when:
    - wireguard_service_enabled | bool
